server:
  port: 8091

druid:
  allow:
    ip: 139.196.102.196
  login:
    user_name: root
    password: root
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.196.102.196:3306/xdclass?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: lynn
    password: Lohk#200801
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-idle: 5
      max-wait-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      pool-prepared-statements: false

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/mapper/**/*.xml
